Jest [rebase, fix errors, tweak config, misc updates]
boujeepossum/react-boilerplate pull request #1
Opened 2016-09-15 17:59 UTC by justingreenberg

2016-09-15 18:04 UTC, dmitriiabramov commented
than you so much for doing this!

that's a lot of commits. let me try to pull it and see what's going on :)

2016-09-15 18:06 UTC, justingreenberg commented
no problem! yea this was a little bit out of sync with development branch lol

2016-09-16 09:45 UTC, andykenward commented on package.json
> +    "test:watch": "cross-env NODE_ENV=test jest --no-cache --coverage",
change to
`"test:watch": "cross-env NODE_ENV=test jest --watch --coverage",`

2016-09-16 09:52 UTC, andykenward commented on package.json
>      "jest": "^15.1.1",
remove `jest` as you have `jest-cli` installed to now

Looking at the repos for both. `jest` is just a wrapper for `jest-cli`. So go with `jest-cli`

[jest-cli](https://github.com/facebook/jest/blob/ec782b567bf343d9d278cd79265a1af2bfc3e83c/packages/jest-cli/package.json)

[jest](https://github.com/facebook/jest/blob/ec782b567bf343d9d278cd79265a1af2bfc3e83c/packages/jest/package.json)

2016-09-16 09:55 UTC, andykenward requested changes
Just some little changes I suggest. 

Also no longer need `internals/webpack/webpack.test.babel.js`

(still getting use to this new review process, not sure about it)

2016-09-16 16:49 UTC, justingreenberg commented
@andykenward thank you! i just pushed up the changes you suggested in 8221fb3... everything seems to be working as expected 👍

2016-09-16 20:45 UTC, dmitriiabramov commented on package.json
> +    "test:watch": "cross-env NODE_ENV=test jest --no-cache --coverage",
i'm not sure how useful `--coverage` is when used with `--watch` right now. It'll report only partial coverage + `0`s for all untested files.

2016-09-16 20:48 UTC, justingreenberg commented on package.json
> +    "test:watch": "cross-env NODE_ENV=test jest --no-cache --coverage",
that makes sense now, i had to pass `--watchAll` to get full coverage report...

https://github.com/dmitriiabramov/react-boilerplate/pull/1/commits/88a41e26bcfa68c79bdc06fc107be22efc5fd08e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45

2016-11-04 17:43 UTC, closed without merging